### ISSUE TITLE
pcb layout

### ISSUE THREAD

**Issue by steveb999** [simonttp78/FlyballETS-Software#75]
Hi, Is there a pcb layout or wiring diagram to support the esp32 version of flyball software ?

**Comment by vyruz1986** [comment]
Yes, it can be found here: https://github.com/vyruz1986/FlyballETS-Hardware/tree/feature/ESP32

**Comment by simonttp78** [comment]
@steveb999 
Hi. My PCB layout still requires optimisation. Had no time recently to work on it so I use prototype PCBes with "manual" patches.
I'm going to add support for charing while system is in use and I'll publish it when done. I can offer one of my prototype PCBes. Send me PM if you're interested.
